#!/usr/bin/env python3
"""Configure Arize AX CLI profile from backend/.env credentials."""

from __future__ import annotations

import os
import subprocess
import sys
import webbrowser
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[1]
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

from app.config import get_settings  # noqa: E402

API_KEYS_URL = "https://app.arize.com/settings/api-keys"
SIGNUP_URL = "https://app.arize.com/auth/join"
ARIZE_DIR = Path.home() / ".arize"
PROFILES_DIR = ARIZE_DIR / "profiles"
ACTIVE_PROFILE_FILE = ARIZE_DIR / ".active_profile"


def main() -> int:
    settings = get_settings()
    if not settings.arize_api_key or not settings.arize_space_id:
        print("Arize credentials missing in backend/.env")
        print(f"  1. Sign up / log in: {SIGNUP_URL}")
        print(f"  2. Create an API key + copy Space ID: {API_KEYS_URL}")
        print("  3. Set ARIZE_API_KEY, ARIZE_SPACE_ID, ARIZE_ENABLED=true in backend/.env")
        print("  4. Re-run: python scripts/setup_arize_auth.py")
        webbrowser.open(API_KEYS_URL)
        return 1

    project = settings.arize_project_name or "orchestrateai"
    space = settings.arize_space_id

    PROFILES_DIR.mkdir(parents=True, exist_ok=True)
    profile_path = PROFILES_DIR / "default.toml"
    profile_path.write_text(
        f"""[profile]
name = "default"

[auth]
auth_method = "api-key"
api_key = "{settings.arize_api_key}"

[routing]
region = ""

[output]
format = "table"

# OrchestrateAI — generated by scripts/setup_arize_auth.py
# project={project} space_id={space[:12]}…
""",
        encoding="utf-8",
    )
    ACTIVE_PROFILE_FILE.write_text("default\n", encoding="utf-8")

    os.environ["ARIZE_API_KEY"] = settings.arize_api_key
    os.environ["ARIZE_SPACE_ID"] = space
    os.environ["ARIZE_PROJECT_NAME"] = project

    print(f"Wrote AX CLI profile → {profile_path}")
    print(f"Arize tracing enabled: {settings.arize_enabled}")

    ax = _find_ax()
    if ax:
        subprocess.run([ax, "profiles", "show"], check=False)
        subprocess.run([ax, "projects", "list"], check=False)
    else:
        print("Install AX CLI: pip install arize-ax-cli  (then: ax projects list)")

    return 0


def _find_ax() -> str | None:
    venv_ax = _BACKEND / ".venv" / "bin" / "ax"
    if venv_ax.is_file():
        return str(venv_ax)
    milestone_ax = Path(
        "/Users/isaksmith/.cursor/worktrees/EventPlannerAgent/milestone-1/backend/.venv/bin/ax"
    )
    if milestone_ax.is_file():
        return str(milestone_ax)
    for path in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(path) / "ax"
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


if __name__ == "__main__":
    raise SystemExit(main())
