// Deliverable tiles (Branding / Website / Outreach), the tiling grid, and the
// maximize modal. Tile bodies render purely from integration-produced data.
import type { DeliverableKey, BrandKit, SiteResult, EmailDraft } from '../types'

export interface Deliverables { branding?: BrandKit; website?: SiteResult; outreach?: EmailDraft[] }
export const ORDER: DeliverableKey[] = ['branding', 'website', 'outreach']
export const META: Record<DeliverableKey, { icon: string; label: string; title: string }> = {
  branding: { icon: '🎨', label: 'Branding', title: '🎨 Your brand' },
  website: { icon: '🌐', label: 'Website', title: '🌐 Your website' },
  outreach: { icon: '✉️', label: 'Outreach', title: '✉️ Sponsor outreach' },
}

function Swatches({ palette, big }: { palette: BrandKit['palette']; big?: boolean }) {
  return (
    <div className="grid grid-cols-4 gap-2">
      {palette.map((c) => (
        <div key={c.hex}>
          <div className="swatch" style={{ background: c.hex, height: big ? 52 : undefined }} />
          {big && (<><div className="mono text-[10px] text-clay mt-1">{c.hex}</div><div className="text-[10px] text-inkSoft">{c.name}</div></>)}
        </div>
      ))}
    </div>
  )
}

function SiteFrame({ site }: { site: SiteResult }) {
  return (
    <div className="rounded-lg border border-line overflow-hidden bg-white relative h-full min-h-[120px]">
      <div className="absolute inset-x-0 top-0 h-5 bg-slate-200 flex items-center gap-1 px-2 z-10">
        <span className="h-2 w-2 rounded-full" style={{ background: '#B2553B' }} />
        <span className="h-2 w-2 rounded-full" style={{ background: '#BC8A2E' }} />
        <span className="h-2 w-2 rounded-full" style={{ background: '#7E8C57' }} />
        <span className="ml-2 text-[9px] text-slate-500 mono truncate">{site.url}</span>
      </div>
      <div className="absolute inset-0 top-5 text-white" style={{ background: 'linear-gradient(135deg,#0a1f44,#08111f)' }}>
        <div className="h-full flex flex-col items-center justify-center text-center px-3 scanline">
          <div className="text-[8px] tracking-[0.3em]" style={{ color: 'rgba(127,211,224,.85)' }}>{site.eyebrow}</div>
          <div className="text-[clamp(14px,2.4vw,26px)] font-bold mt-1">{site.title}</div>
          <div className="text-[10px] text-slate-300 mt-1">{site.subtitle}</div>
          <button className="mt-2.5 text-[10px] font-semibold px-3 py-1 rounded-full" style={{ background: '#22d3ee', color: '#0a1f44' }}>Register →</button>
        </div>
      </div>
    </div>
  )
}

function AssetTile({ label, glyph }: { label: string; glyph: string }) {
  return (
    <div className="rounded-lg border border-line bg-surface2 overflow-hidden">
      <div className="h-full grid place-items-center text-[10px] scanline" style={{ background: 'linear-gradient(120deg,#0a1f44,#08111f)', minHeight: 64, color: 'rgba(34,211,238,.7)' }}>{glyph}</div>
      <div className="text-[10px] text-inkSoft px-2 py-1 border-t border-line">{label}</div>
    </div>
  )
}

export function TileBody({ k, deliverables, full }: { k: DeliverableKey; deliverables: Deliverables; full?: boolean }) {
  if (k === 'branding') {
    const kit = deliverables.branding
    if (!kit) return null
    if (!full) return (
      <div className="p-3 space-y-3 h-full flex flex-col">
        <div className="flex gap-3 items-center">
          <div className="h-14 w-14 shrink-0 rounded-xl border border-line flex items-center justify-center font-bold" style={{ background: kit.logo.bg, color: '#22d3ee' }}>
            <span className="whitespace-nowrap text-sm">B<span style={{ color: kit.logo.accent }}>/</span>AI</span>
          </div>
          <div className="flex-1"><Swatches palette={kit.palette} /></div>
        </div>
        <div className="rounded-lg border border-line scanline grid place-items-center text-[10px] flex-1 min-h-[48px]" style={{ background: 'linear-gradient(120deg,#0a1f44,#08111f)', color: 'rgba(34,211,238,.7)' }}>◢◤ background graphic</div>
        <div className="text-[10px] text-inkSoft">5 assets · Midjourney · {kit.vibe}</div>
      </div>
    )
    return (
      <div className="space-y-5">
        <div className="flex gap-4 items-center">
          <div className="h-24 w-24 rounded-2xl border border-line grid place-items-center font-bold text-3xl" style={{ background: kit.logo.bg, color: '#22d3ee' }}>B<span style={{ color: kit.logo.accent }}>/</span>AI</div>
          <div><div className="text-lg font-semibold">Berkeley AI Hackathon</div><div className="text-inkSoft text-sm">{kit.vibe}</div><div className="text-inkSoft text-xs mt-1">Logo mark · generated by Midjourney</div></div>
        </div>
        <div><div className="text-sm font-semibold mb-2">Color palette</div><Swatches palette={kit.palette} big /></div>
        <div>
          <div className="text-sm font-semibold mb-2">Brand assets</div>
          <div className="grid grid-cols-3 gap-3" style={{ gridAutoRows: '110px' }}>
            {kit.assets.map((a) => <AssetTile key={a.label} label={a.label} glyph={a.glyph} />)}
          </div>
          <div className="text-[11px] text-inkSoft mt-2">Images &amp; motion generated by Midjourney to one design seed for consistency.</div>
        </div>
      </div>
    )
  }

  if (k === 'website') {
    const site = deliverables.website
    if (!site) return null
    if (!full) return (
      <div className="p-3 h-full flex flex-col gap-2">
        <div className="flex-1 min-h-0"><SiteFrame site={site} /></div>
        <div className="flex items-center justify-between">
          <span className="text-[10px] text-inkSoft">Live registration site</span>
          <span className="text-[10px] px-2 py-0.5 rounded bg-surface2 text-clay border border-line mono">{site.url}</span>
        </div>
      </div>
    )
    return (
      <div className="space-y-4">
        <div className="h-[42vh] min-h-[260px]"><SiteFrame site={site} /></div>
        <div className="flex items-center gap-3">
          <a href="#" onClick={(e) => e.preventDefault()} className="text-[12px] px-3 py-1.5 rounded-md text-surface" style={{ background: '#B05E40' }}>Open site ↗</a>
          <span className="mono text-[12px] text-clay">{site.url}</span>
        </div>
        <div className="grid grid-cols-3 gap-3 text-[12px]">
          <div className="rounded-lg border border-line bg-surface2 p-3"><div className="font-medium">Registration form</div><div className="text-inkSoft mt-1">name · email · team · track</div></div>
          <div className="rounded-lg border border-line bg-surface2 p-3"><div className="font-medium">Sections</div><div className="text-inkSoft mt-1">hero · schedule · prizes · FAQ</div></div>
          <div className="rounded-lg border border-line bg-surface2 p-3"><div className="font-medium">Deploy</div><div className="text-inkSoft mt-1">Claude Code → Vercel</div></div>
        </div>
      </div>
    )
  }

  const mails = deliverables.outreach
  if (!mails) return null
  if (!full) return (
    <div className="p-3 space-y-2 h-full flex flex-col">
      {mails.map((e) => (
        <div key={e.to} className="rounded-lg border border-line bg-surface2 p-2">
          <div className="text-[12px] truncate">{e.subject}</div>
          <div className="text-[10px] text-inkSoft truncate">{e.to}</div>
        </div>
      ))}
      <div className="text-[10px] mt-auto rounded p-1.5" style={{ color: '#8f3f28', background: 'rgba(178,85,59,.08)', border: '1px solid rgba(178,85,59,.25)' }}>Drafts only — approve in chat to send.</div>
    </div>
  )
  return (
    <div className="space-y-3">
      {mails.map((e) => (
        <div key={e.to} className="rounded-xl border border-line bg-surface2 p-4">
          <div className="flex items-center gap-2"><span className="text-sm font-medium">{e.subject}</span>
            <span className="ml-auto text-[9px] px-1.5 py-0.5 rounded" style={{ color: '#8f3f28', background: 'rgba(178,85,59,.1)', border: '1px solid rgba(178,85,59,.3)' }}>DRAFT · awaiting your OK</span></div>
          <div className="text-[11px] text-inkSoft mt-0.5 mono">to: {e.to}</div>
          <div className="text-[12px] mt-2 whitespace-pre-line leading-relaxed">{e.body}</div>
        </div>
      ))}
      <div className="text-[12px] rounded-lg p-2.5" style={{ color: '#8f3f28', background: 'rgba(178,85,59,.08)', border: '1px solid rgba(178,85,59,.22)' }}>Nothing sends until you approve it in the chat — that's a Tier 3 human handoff.</div>
    </div>
  )
}

export function TileGrid({ open, deliverables, cols, onMaximize, onClose }: {
  open: DeliverableKey[]; deliverables: Deliverables; cols: number
  onMaximize: (k: DeliverableKey) => void; onClose: (k: DeliverableKey) => void
}) {
  return (
    <div className="h-full flex-1" style={{ display: 'grid', gap: 14, gridAutoRows: 'minmax(0,1fr)', gridTemplateColumns: `repeat(${cols}, minmax(0,1fr))` }}>
      {open.map((k) => (
        <div key={k} className="tile tile-in rounded-2xl border border-line bg-surface soft">
          <div className="tile-head">
            <span className="text-sm font-semibold">{META[k].title}</span>
            <button className="tbtn ml-auto" title="Maximize" onClick={() => onMaximize(k)}>⤢</button>
            <button className="tbtn" title="Close" onClick={() => onClose(k)}>×</button>
          </div>
          <div className="tile-body"><TileBody k={k} deliverables={deliverables} /></div>
        </div>
      ))}
    </div>
  )
}

export function MaximizeModal({ k, deliverables, onClose }: { k: DeliverableKey | null; deliverables: Deliverables; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-[60] transition-opacity duration-200" style={{ opacity: k ? 1 : 0, pointerEvents: k ? 'auto' : 'none' }}>
      <div className="absolute inset-0" style={{ background: 'rgba(27,26,23,.45)' }} onClick={onClose} />
      <div className="absolute inset-0 flex items-center justify-center p-4 md:p-8">
        <div className="relative w-full max-w-5xl h-[88vh] bg-surface border border-line rounded-2xl overflow-hidden flex flex-col soft">
          <div className="px-5 py-3 border-b border-line flex items-center gap-2 flex-none bg-surface2">
            <h3 className="text-sm font-semibold">{k ? META[k].title : ''}</h3>
            <button className="ml-auto h-8 w-8 rounded-md border border-line text-inkSoft hover:bg-surface2" onClick={onClose}>×</button>
          </div>
          <div className="flex-1 min-h-0 overflow-y-auto p-5">{k && <TileBody k={k} deliverables={deliverables} full />}</div>
        </div>
      </div>
    </div>
  )
}
